In [25]:
import sys  
sys.path.insert(0, '..')

from datetime import date, timedelta

from config import Config

import pandas as pd
import numpy as np
from sqlalchemy import create_engine

db = create_engine(Config.SQLALCHEMY_DATABASE_URI)

In [2]:
pozitivity = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=0, usecols=['tyden', 'vek_kategorie', 'pozitivni_celkem', 'pozitivni_bez_ockovani', 'pozitivni_po_prvni', 'pozitivni_po_ukonceni', 'pozitivni_po_ukonceni_s_posilujici'])
hospitalizace = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=1, usecols=['tyden', 'vek_kategorie', 'hospitalizace_celkem', 'hospitalizace_bez_ockovani', 'hospitalizace_po_prvni', 'hospitalizace_po_ukonceni', 'hospitalizace_po_ukonceni_s_posilujici'])
jip = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=2, usecols=['tyden', 'vek_kategorie', 'JIP_celkem', 'JIP_bez_ockovani', 'JIP_po_prvni', 'JIP_po_ukonceni', 'JIP_po_ukonceni_s_posilujici'])

In [3]:
df = pd.merge(pozitivity, hospitalizace)
df = pd.merge(df, jip)
df

,tyden,vek_kategorie,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54 let,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79 let,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44 let,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24 let,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89 let,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69 let,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84 let,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74 let,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69 let,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89 let,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [4]:
df = df.rename({'vek_kategorie': 'vekova_skupina'}, axis='columns')
df['vekova_skupina'] = df['vekova_skupina'].str.replace(' let', '')
df

,tyden,vekova_skupina,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [5]:
df['vekova_skupina'] = df['vekova_skupina'].str.replace(' let', '')
df

,tyden,vekova_skupina,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [43]:
srovnani = pd.read_sql_query(
    f"""
    select * from srovnani_ockovani s 
    where s.od < '2021-10-28'
    """,
    db
)

srovnani = srovnani[srovnani['od'] == srovnani['od'].max()]
srovnani['vekova_skupina'] = srovnani['vekova_skupina'].replace({'80-84': '80+', '85-89': '80+', '90+': '80+'})
srovnani = srovnani.groupby(['tyden', 'od', 'do', 'vekova_skupina']).sum().reset_index()

srovnani

,tyden,od,do,vekova_skupina,nakazeni_celkem,nakazeni_bez,nakazeni_castecne,nakazeni_plne,nakazeni_posilujici,hospitalizace_celkem,hospitalizace_bez,hospitalizace_castecne,hospitalizace_plne,hospitalizace_posilujici,hospitalizace_jip_celkem,hospitalizace_jip_bez,hospitalizace_jip_castecne,hospitalizace_jip_plne,hospitalizace_jip_posilujici
0,2021-42,2021-10-18,2021-10-24,15-19,1998,1791,42,165,0,5,5,0,0,0,1,1,0,0,0
1,2021-42,2021-10-18,2021-10-24,25-29,1145,894,23,228,0,15,15,0,0,0,1,1,0,0,0
2,2021-42,2021-10-18,2021-10-24,30-34,1335,1015,18,302,0,18,16,1,1,0,2,1,0,1,0
3,2021-42,2021-10-18,2021-10-24,35-39,1583,1070,25,488,0,28,25,1,2,0,1,1,0,0,0
4,2021-42,2021-10-18,2021-10-24,40-44,2032,1202,22,808,0,24,20,0,4,0,3,2,0,1,0
5,2021-42,2021-10-18,2021-10-24,45-49,1858,1107,20,730,1,50,45,0,4,1,8,6,0,1,1
6,2021-42,2021-10-18,2021-10-24,50-54,1117,633,12,472,0,39,29,1,9,0,7,4,0,3,0
7,2021-42,2021-10-18,2021-10-24,55-59,932,499,10,422,1,44,33,2,8,1,8,7,0,1,0
8,2021-42,2021-10-18,2021-10-24,60-64,632,268,5,358,1,50,39,0,11,0,10,10,0,0,0
9,2021-42,2021-10-18,2021-10-24,65-69,515,202,6,307,0,73,43,1,29,0,15,10,1,4,0
10,2021-42,2021-10-18,2021-10-24,70-74,478,129,3,346,0,108,55,1,52,0,18,7,1,10,0
11,2021-42,2021-10-18,2021-10-24,75-79,431,126,5,299,1,133,54,4,74,1,14,5,1,8,0
12,2021-42,2021-10-18,2021-10-24,80+,431,130,5,296,0,182,79,3,100,0,12,3,0,9,0

In [44]:
populace = pd.read_sql_query(
    """
    select vekova_skupina, sum(pocet) populace, min_vek
        from populace p 
        join populace_kategorie k on (k.min_vek <= vek and k.max_vek >= vek)
        where orp_kod = 'CZ0'
        group by vekova_skupina
    """, 
db)
populace

   vekova_skupina   populace  min_vek
0           60-64   625465.0       60
1           18-24   669492.0       18
2           25-29   620925.0       25
3           65-69   672418.0       65
4           45-49   882586.0       45
5           40-44   893321.0       40
6           50-54   691083.0       50
7           16-17   195016.0       16
8           75-79   417201.0       75
9           70-74   621177.0       70
10            80+   447526.0       80
11          55-59   669733.0       55
12          35-39   753310.0       35
13          12-15   456488.0       12
14           0-11  1367105.0        0
15          30-34   718931.0       30

In [45]:
ockovani = pd.read_sql_query(
    f"""
    select datum, vekova_skupina,
        sum(case when poradi_davky = 1 then pocet else 0 end) populace_ockovani, 
        sum(case when poradi_davky = v.davky then pocet else 0 end) populace_plne, 
        sum(case when poradi_davky = 3 then pocet else 0 end) populace_posilujici
    from ockovani_lide o
    join vakciny v on (o.vakcina = v.vakcina)
    where datum < '2021-10-25'
    group by datum, vekova_skupina
    """,
    db
)
ockovani = ockovani.groupby(['vekova_skupina', 'datum']).sum().groupby(level=0).cumsum().reset_index()
ockovani

,vekova_skupina,datum,populace_ockovani,populace_plne,populace_posilujici
0,0-11,2021-10-01,1,0,0
1,12-15,2021-01-19,1,0,0
2,12-15,2021-02-17,1,1,0
3,12-15,2021-02-23,2,1,0
4,12-15,2021-02-26,3,1,0
...,...,...,...,...,...
4298,80+,2021-10-13,363651,362095,5353
4299,80+,2021-10-14,363716,362181,6798
4300,80+,2021-10-15,363762,362255,8144
4301,80+,2021-10-16,363766,362262,8596
4302,80+,2021-10-17,363774,362269,8830

In [40]:
df = pd.merge(ockovani, populace)
df = pd.merge(df, srovnani, left_on=['datum', 'vekova_skupina'], right_on=['od', 'vekova_skupina'])



df['vekova_skupina'] = df['vekova_skupina'].replace({'25-29': '25-39', '30-34': '25-39', '35-39': '25-39', '40-44': '40-49', '45-49': '40-49', '50-54': '50-59', '55-59': '50-59', 
                                                     '60-64': '60-69', '65-69': '60-69', '70-74': '70-79', '75-79': '70-79'})

df.groupby(['datum', 'tyden', 'od', 'do', 'vekova_skupina']).sum().reset_index()

df = df[df['datum'] == df['datum'].max()]

df['populace_bez'] = df['populace'] - df['populace_ockovani']
df['populace_plne'] = df['populace_plne']

df

,vekova_skupina,datum,populace_ockovani,populace_plne,populace_posilujici,populace,min_vek,tyden,od,do,...,hospitalizace_bez,hospitalizace_castecne,hospitalizace_plne,hospitalizace_posilujici,hospitalizace_jip_celkem,hospitalizace_jip_bez,hospitalizace_jip_castecne,hospitalizace_jip_plne,hospitalizace_jip_posilujici,populace_bez
25,25-39,2021-10-11,299333,288639,942,620925.0,25,2021-41,2021-10-11,2021-10-17,...,4,0,0,0,1,1,0,0,0,321592.0
58,25-39,2021-10-11,366536,355556,1187,718931.0,30,2021-41,2021-10-11,2021-10-17,...,13,0,1,0,1,1,0,0,0,352395.0
86,25-39,2021-10-11,414617,404602,1522,753310.0,35,2021-41,2021-10-11,2021-10-17,...,10,0,2,0,1,1,0,0,0,338693.0
121,40-49,2021-10-11,552985,541233,2312,893321.0,40,2021-41,2021-10-11,2021-10-17,...,26,1,4,0,4,4,0,0,0,340336.0
157,40-49,2021-10-11,602721,597534,2932,882586.0,45,2021-41,2021-10-11,2021-10-17,...,26,0,6,0,6,5,0,1,0,279865.0
187,50-59,2021-10-11,484392,479971,2526,691083.0,50,2021-41,2021-10-11,2021-10-17,...,20,0,3,0,6,5,0,1,0,206691.0
225,50-59,2021-10-11,486307,482116,2491,669733.0,55,2021-41,2021-10-11,2021-10-17,...,19,0,1,0,7,7,0,0,0,183426.0
263,60-69,2021-10-11,474063,466637,2374,625465.0,60,2021-41,2021-10-11,2021-10-17,...,28,1,7,0,12,8,0,4,0,151402.0
302,60-69,2021-10-11,546519,540186,1985,672418.0,65,2021-41,2021-10-11,2021-10-17,...,30,0,12,0,14,12,0,2,0,125899.0
340,70-79,2021-10-11,530023,526203,1334,621177.0,70,2021-41,2021-10-11,2021-10-17,...,22,4,21,0,13,8,2,3,0,91154.0
380,70-79,2021-10-11,360519,360846,857,417201.0,75,2021-41,2021-10-11,2021-10-17,...,29,0,37,0,13,6,0,7,0,56682.0
481,80+,2021-10-11,363530,361956,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,8,1,21,0,4,1,0,3,0,83996.0
482,80+,2021-10-11,363530,361956,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,15,0,16,0,5,2,0,3,0,83996.0
483,80+,2021-10-11,363530,361956,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,20,1,30,0,11,5,1,5,0,83996.0

In [31]:
df_norm = df.copy()

df_norm['vekova_skupina'] = df_norm['vekova_skupina'].replace({})

datasets = ['nakazeni', 'hospitalizace', 'hospitalizace_jip']
groups = ['bez', 'castecne', 'plne', 'posilujici']

for d in datasets:
    for g in groups:
        df_norm[d + '_' + g + '_norm'] = ((100000 * df_norm[d + '_' + g]) / df_norm['populace_' + g]).replace({np.nan: 0})
        
df_norm

,vekova_skupina,datum,populace_ockovani,populace_plne,populace_posilujici,populace,min_vek,tyden,od,do,...,nakazeni_plne_norm,nakazeni_posilujici_norm,hospitalizace_bez_norm,hospitalizace_castecne_norm,hospitalizace_plne_norm,hospitalizace_posilujici_norm,hospitalizace_jip_bez_norm,hospitalizace_jip_castecne_norm,hospitalizace_jip_plne_norm,hospitalizace_jip_posilujici_norm
0,25-39,2020-12-28,311,0,0,620925.0,25,2020-53,2020-12-28,2021-01-03,...,0.000000,0.0,7.895407,0.000000,0.000000,0.0,0.483392,0.000000,0.000000,0.0
1,25-39,2021-01-04,1529,0,0,620925.0,25,2021-01,2021-01-04,2021-01-10,...,0.000000,0.0,5.650666,0.000000,0.000000,0.0,0.322895,0.000000,0.000000,0.0
2,25-39,2021-01-11,4577,1,0,620925.0,25,2021-02,2021-01-11,2021-01-17,...,0.000000,0.0,5.354118,0.000000,0.000000,0.0,0.648984,0.000000,0.000000,0.0
3,25-39,2021-01-18,7685,216,0,620925.0,25,2021-03,2021-01-18,2021-01-24,...,0.000000,0.0,5.707390,0.000000,0.000000,0.0,0.489205,0.000000,0.000000,0.0
4,25-39,2021-01-25,9052,1309,0,620925.0,25,2021-04,2021-01-25,2021-01-31,...,0.000000,0.0,6.210439,0.000000,0.000000,0.0,0.490298,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,80+,2021-10-04,363206,360823,692,447526.0,80,2021-40,2021-10-04,2021-10-10,...,6.374316,0.0,3.557875,0.000000,0.831433,0.0,1.185958,0.000000,0.000000,0.0
480,80+,2021-10-04,363206,360823,692,447526.0,80,2021-40,2021-10-04,2021-10-10,...,14.965787,0.0,18.975332,0.000000,4.434307,0.0,1.185958,0.000000,1.108577,0.0
481,80+,2021-10-11,363530,359076,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,12.810658,0.0,9.524263,63.532402,5.848344,0.0,1.190533,0.000000,0.835478,0.0
482,80+,2021-10-11,363530,359076,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,10.025733,0.0,17.857993,0.000000,4.455881,0.0,2.381066,0.000000,0.835478,0.0
483,80+,2021-10-11,363530,359076,2880,447526.0,80,2021-41,2021-10-11,2021-10-17,...,22.000913,0.0,23.810658,63.532402,8.354777,0.0,5.952664,63.532402,1.392463,0.0