In [1]:
import sys  
sys.path.insert(0, '..')

from datetime import date, timedelta

from config import Config

import pandas as pd
from sqlalchemy import create_engine

db = create_engine(Config.SQLALCHEMY_DATABASE_URI)

In [2]:
pozitivity = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=0, usecols=['tyden', 'vek_kategorie', 'pozitivni_celkem', 'pozitivni_bez_ockovani', 'pozitivni_po_prvni', 'pozitivni_po_ukonceni', 'pozitivni_po_ukonceni_s_posilujici'])
hospitalizace = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=1, usecols=['tyden', 'vek_kategorie', 'hospitalizace_celkem', 'hospitalizace_bez_ockovani', 'hospitalizace_po_prvni', 'hospitalizace_po_ukonceni', 'hospitalizace_po_ukonceni_s_posilujici'])
jip = pd.read_excel('../data/ockovani-pozitivity-hospitalizace-jip.xlsx', sheet_name=2, usecols=['tyden', 'vek_kategorie', 'JIP_celkem', 'JIP_bez_ockovani', 'JIP_po_prvni', 'JIP_po_ukonceni', 'JIP_po_ukonceni_s_posilujici'])

In [3]:
df = pd.merge(pozitivity, hospitalizace)
df = pd.merge(df, jip)
df

,tyden,vek_kategorie,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54 let,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79 let,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44 let,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24 let,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89 let,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69 let,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84 let,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74 let,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69 let,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89 let,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [4]:
df = df.rename({'vek_kategorie': 'vekova_skupina'}, axis='columns')
df['vekova_skupina'] = df['vekova_skupina'].str.replace(' let', '')
df

,tyden,vekova_skupina,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [5]:
df['vekova_skupina'] = df['vekova_skupina'].str.replace(' let', '')
df

,tyden,vekova_skupina,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,50-54,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,75-79,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,40-44,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,20-24,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,85-89,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,65-69,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,80-84,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,70-74,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,65-69,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,85-89,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [6]:
srovnani = pd.read_sql_query(
    f"""
    select * from srovnani_ockovani s 
    where s.od < '2021-10-25'
    """,
    db.engine
)
srovnani

,tyden,od,do,vekova_skupina,pozitivni_celkem,pozitivni_bez_ockovani,pozitivni_po_prvni,pozitivni_po_ukonceni,pozitivni_po_ukonceni_s_posilujici,hospitalizace_celkem,hospitalizace_bez_ockovani,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici
0,2020-53,2020-12-28,2021-01-03,50-54,5959,5946,13,0,0,219,219,0,0,0,42,42,0,0,0
1,2021-34,2021-08-23,2021-08-29,75-79,10,1,0,9,0,4,3,0,1,0,1,1,0,0,0
2,2021-11,2021-03-15,2021-03-21,40-44,5988,5862,112,14,0,207,199,6,2,0,49,47,1,1,0
3,2021-12,2021-03-22,2021-03-28,20-24,2783,2745,33,5,0,21,20,0,1,0,2,2,0,0,0
4,2021-29,2021-07-19,2021-07-25,85-89,5,3,0,2,0,4,3,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,2021-01,2021-01-04,2021-01-10,65-69,4996,4984,12,0,0,693,693,0,0,0,174,174,0,0,0
535,2021-03,2021-01-18,2021-01-24,80-84,1062,1021,41,0,0,524,509,15,0,0,74,70,4,0,0
536,2021-41,2021-10-11,2021-10-17,70-74,198,52,5,141,0,47,22,4,21,0,13,8,2,3,0
537,2021-15,2021-04-12,2021-04-18,65-69,1132,1068,57,7,0,327,311,14,2,0,92,90,2,0,0
538,2021-24,2021-06-14,2021-06-20,85-89,12,6,4,2,0,6,3,2,1,0,2,1,0,1,0

In [19]:
populace = pd.read_sql_query(
    """
    select vekova_skupina, sum(pocet) populace, min_vek
        from populace p 
        join populace_kategorie k on (k.min_vek <= vek and k.max_vek >= vek)
        where orp_kod = 'CZ0'
        group by vekova_skupina
    """, 
db)
populace

   vekova_skupina   populace  min_vek
0           60-64   625465.0       60
1           18-24   669492.0       18
2           25-29   620925.0       25
3           65-69   672418.0       65
4           45-49   882586.0       45
5           40-44   893321.0       40
6           50-54   691083.0       50
7           16-17   195016.0       16
8           75-79   417201.0       75
9           70-74   621177.0       70
10            80+   447526.0       80
11          55-59   669733.0       55
12          35-39   753310.0       35
13          12-15   456488.0       12
14           0-11  1367105.0        0
15          30-34   718931.0       30

In [20]:
ockovani = pd.read_sql_query(
    f"""
    select datum, vekova_skupina,
        sum(case when poradi_davky = 1 then pocet else 0 end) populace_ockovani, 
        sum(case when poradi_davky = v.davky then pocet else 0 end) populace_plne, 
        sum(case when poradi_davky = 3 then pocet else 0 end) populace_posilujici
    from ockovani_lide o
    join vakciny v on (o.vakcina = v.vakcina)
    where datum < '2021-10-25'
    group by datum, vekova_skupina
    """,
    db
)
ockovani = ockovani.groupby(['vekova_skupina', 'datum']).sum().groupby(level=0).cumsum().reset_index()
ockovani

,vekova_skupina,datum,populace_ockovani,populace_plne,populace_posilujici
0,0-11,2021-10-01,1,0,0
1,12-15,2021-01-19,1,0,0
2,12-15,2021-02-17,1,1,0
3,12-15,2021-02-23,2,1,0
4,12-15,2021-02-26,3,1,0
...,...,...,...,...,...
4298,80+,2021-10-13,363651,362095,5353
4299,80+,2021-10-14,363716,362181,6798
4300,80+,2021-10-15,363762,362255,8144
4301,80+,2021-10-16,363766,362262,8596
4302,80+,2021-10-17,363774,362269,8830

In [22]:
df = pd.merge(ockovani, populace)
df = pd.merge(df, srovnani, left_on='datum', right_on='od')

df['populace_bez'] = df['populace'] - df['populace_ockovani']
df['populace_castecne'] = df['populace_ockovani'] - df['populace_plne']
df['populace_plne'] = df['populace_plne'] - df['populace_posilujici']

df

,vekova_skupina_x,datum,populace_ockovani,populace_plne,populace_posilujici,populace,min_vek,tyden,od,do,...,hospitalizace_po_prvni,hospitalizace_po_ukonceni,hospitalizace_po_ukonceni_s_posilujici,JIP_celkem,JIP_bez_ockovani,JIP_po_prvni,JIP_po_ukonceni,JIP_po_ukonceni_s_posilujici,populace_bez,populace_castecne
0,12-15,2021-04-26,20,6,0,456488.0,12,2021-17,2021-04-26,2021-05-02,...,12,0,0,46,39,7,0,0,456468.0,14
1,12-15,2021-04-26,20,6,0,456488.0,12,2021-17,2021-04-26,2021-05-02,...,31,11,0,17,12,5,0,0,456468.0,14
2,12-15,2021-04-26,20,6,0,456488.0,12,2021-17,2021-04-26,2021-05-02,...,43,4,0,56,45,11,0,0,456468.0,14
3,12-15,2021-04-26,20,6,0,456488.0,12,2021-17,2021-04-26,2021-05-02,...,0,0,0,8,8,0,0,0,456468.0,14
4,12-15,2021-04-26,20,6,0,456488.0,12,2021-17,2021-04-26,2021-05-02,...,5,0,0,9,9,0,0,0,456468.0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7555,80+,2021-01-04,766,0,0,447526.0,80,2021-01,2021-01-04,2021-01-10,...,1,0,0,187,187,0,0,0,446760.0,766
7556,80+,2021-01-04,766,0,0,447526.0,80,2021-01,2021-01-04,2021-01-10,...,0,0,0,14,14,0,0,0,446760.0,766
7557,80+,2021-01-04,766,0,0,447526.0,80,2021-01,2021-01-04,2021-01-10,...,3,1,0,89,89,0,0,0,446760.0,766
7558,80+,2021-01-04,766,0,0,447526.0,80,2021-01,2021-01-04,2021-01-10,...,0,0,0,79,79,0,0,0,446760.0,766
7559,80+,2021-01-04,766,0,0,447526.0,80,2021-01,2021-01-04,2021-01-10,...,0,0,0,174,174,0,0,0,446760.0,766

In [ ]:
df_vek = df.copy()

datasets = ['nakazeni', 'hospitalizace', 'hospitalizace_jip']
groups = ['bez', 'castecne', 'plne', 'posilujici']

for d in datasets:
    for g in groups:
        df_vek[d + '_' + g + '_mult'] = df_vek[d + '_' + g] * df_vek[d + '_' + g + '_vek']

df_vek = df_vek.rolling(7, on='datum').sum()

for d in datasets:
    for g in groups:
        df_vek[d + '_' + g + '_vek'] = df_vek[d + '_' + g + '_mult'] / df_vek[d + '_' + g]
        df_vek[d + '_' + g + '_vek'] = df_vek[d + '_' + g + '_vek'].replace({np.nan: None})

for d in datasets:
    df_vek[d + '_celkem_vek'] = sum([df_vek[d + '_' + g + '_mult'] for g in groups]) / df_vek[d + '_celkem']
    df_vek[d + '_celkem_vek'] = df_vek[d + '_celkem_vek'].replace({np.nan: None})

for g in groups:
    df_vek['populace_' + g + '_zastoupeni'] = df_vek['populace_' + g] / df_vek['populace']